# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Documents\Programmation\PublicProject\patcher_VLR_PC\ihm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 200)
        MainWindow.setMinimumSize(QtCore.QSize(642, 200))
        MainWindow.setMaximumSize(QtCore.QSize(642, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ressource/DreamteamLogo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_process = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_process.setGeometry(QtCore.QRect(300, 40, 75, 23))
        self.pushButton_process.setMaximumSize(QtCore.QSize(16777215, 16777211))
        self.pushButton_process.setObjectName("pushButton_process")
        self.pushButton_browse = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browse.setGeometry(QtCore.QRect(560, 10, 75, 23))
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.label_done = QtWidgets.QLabel(self.centralwidget)
        self.label_done.setGeometry(QtCore.QRect(380, 40, 121, 20))
        self.label_done.setObjectName("label_done")
        self.label_process = QtWidgets.QLabel(self.centralwidget)
        self.label_process.setGeometry(QtCore.QRect(380, 40, 251, 21))
        self.label_process.setObjectName("label_process")
        self.fileEdit_path = FileEdit(self.centralwidget)
        self.fileEdit_path.setGeometry(QtCore.QRect(10, 10, 541, 20))
        self.fileEdit_path.setObjectName("fileEdit_path")
        self.pushButton_choix_fichier = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_choix_fichier.setGeometry(QtCore.QRect(20, 40, 91, 23))
        self.pushButton_choix_fichier.setObjectName("pushButton_choix_fichier")
        self.pushButton_choix_image = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_choix_image.setEnabled(False)
        self.pushButton_choix_image.setGeometry(QtCore.QRect(120, 40, 91, 23))
        self.pushButton_choix_image.setObjectName("pushButton_choix_image")
        self.checkBox_fichiers = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_fichiers.setGeometry(QtCore.QRect(20, 80, 441, 17))
        self.checkBox_fichiers.setChecked(True)
        self.checkBox_fichiers.setTristate(False)
        self.checkBox_fichiers.setObjectName("checkBox_fichiers")
        self.checkBox_images = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_images.setEnabled(False)
        self.checkBox_images.setGeometry(QtCore.QRect(20, 110, 441, 17))
        self.checkBox_images.setObjectName("checkBox_images")
        self.checkBox_imagesDDS = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_imagesDDS.setEnabled(False)
        self.checkBox_imagesDDS.setGeometry(QtCore.QRect(20, 140, 521, 17))
        self.checkBox_imagesDDS.setObjectName("checkBox_imagesDDS")
        self.checkBox_videos = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_videos.setEnabled(False)
        self.checkBox_videos.setGeometry(QtCore.QRect(20, 170, 501, 20))
        self.checkBox_videos.setObjectName("checkBox_videos")
        self.pushButton_process.raise_()
        self.pushButton_browse.raise_()
        self.fileEdit_path.raise_()
        self.pushButton_choix_fichier.raise_()
        self.pushButton_choix_image.raise_()
        self.label_done.raise_()
        self.label_process.raise_()
        self.checkBox_fichiers.raise_()
        self.checkBox_images.raise_()
        self.checkBox_imagesDDS.raise_()
        self.checkBox_videos.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_browse, self.pushButton_process)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VLR patch automatique"))
        self.pushButton_process.setText(_translate("MainWindow", "Démarrer"))
        self.pushButton_browse.setText(_translate("MainWindow", "browse"))
        self.label_done.setText(_translate("MainWindow", "Terminé !"))
        self.label_process.setText(_translate("MainWindow", "in process..."))
        self.pushButton_choix_fichier.setText(_translate("MainWindow", "Choisir fichiers"))
        self.pushButton_choix_image.setText(_translate("MainWindow", "Choisir images"))
        self.checkBox_fichiers.setText(_translate("MainWindow", "Update tous les fichiers textes"))
        self.checkBox_images.setText(_translate("MainWindow", "Update tous les PNG (petites images)"))
        self.checkBox_imagesDDS.setText(_translate("MainWindow", "Update tous  les DDS (images de fond)"))
        self.checkBox_videos.setText(_translate("MainWindow", "Update les vidéos"))
from fileEdit import FileEdit
import ressource_rc
